### ISSUE TITLE
Could you elaborate on how you fixed tmux-resurrect with this plugin

### ISSUE THREAD

**Issue by tonywoode** [AdrieanKhisbe/zsh-quiet-accept-line#1]
> This plugin was driven by the need to improve tmux-resurrect zsh history saving that was poluting terminal with fc commands

Awesome work! But you don't seem to have a fork of tmux-resurrect and I don't see you on any of the related issues there. I commented on this yesterday, would you care to help:
https://github.com/tmux-plugins/tmux-resurrect/issues/278

thanks

**Comment by AdrieanKhisbe** [comment]
Sorry @tonywoode for that very late answer.

To be frank I don't remember much not having really used tmux theses last days. 😕 

But if I remember well, there is no need: **ZQAL, ensure that the command you launch does not get written into history, and is not preserved on the screen.**
By doing so, tmux-resurrect is blind to this command.
